//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjHw2new.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TableBooks1091735
    {
        [DisplayName("ISBN編號")]
        [Required(ErrorMessage = "ISBN編號不可空白")]
        [StringLength(14, ErrorMessage = "ISBN編號必須是13個字元", MinimumLength = 13)]
        public string fBookISBN { get; set; }

        [DisplayName("書名")]
        [Required(ErrorMessage = "書名不可空白")]
        public string fBookName { get; set; }

        [DisplayName("作者")]
        public string fBookAuthor { get; set; }

        [DisplayName("出版社")]
        public string fBookPublisher { get; set; }

        [DisplayName("售價")]
        [Required(ErrorMessage = "售價不可空白")]
        public int fPrice { get; set; }
    }
}
